# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

Full finetuned
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Meta-Llama-3.1-8B-Instruct/
  checkpoint_files: [
     /tmp/torchtune/llama3_1_8B/lora_single_device/epoch_0/ft-model-00001-of-00004.safetensors,
     /tmp/torchtune/llama3_1_8B/lora_single_device/epoch_0/ft-model-00002-of-00004.safetensors,
     /tmp/torchtune/llama3_1_8B/lora_single_device/epoch_0/ft-model-00003-of-00004.safetensors,
     /tmp/torchtune/llama3_1_8B/lora_single_device/epoch_0/ft-model-00004-of-00004.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: output
  model_type: LLAMA3

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
  max_seq_len: 512

# Environment
device: hpu
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed
compile: True
# EleutherAI specific eval args
tasks: ["hellaswag"]
limit: null
max_seq_length: 512
batch_size: 32
enable_kv_cache: True

# Quantization specific args
quantizer: null
